### ISSUE TITLE
Colour for the vt100 logo

### ISSUE THREAD

**Issue by ausil** [kidmirage/2-3-Scale-VT100-Terminal-Reproduction#1]
I appreciate the effort you put into this, I was wondering what colour you used for the vt100 text on the logo, I would ask on Instructables but I have an account here so it is easier. Interestingly my LCD does 1152x864 even though everything indicates it should be 1024x768

**Comment by kidmirage** [comment]
Hey Dennis, 

I wish I could help with the exact color but in fact I just found some orange PLA in a sample pack of filaments that I think came with my 3D pen. Sorry. 

Mike

**Comment by kidmirage** [comment]
Did you get a PIM372 display?  I was expecting mine to be monochrome based on the Digi-Key description and was pleasantly surprised it was color. I’ll have to check the resolution as well. 

M

**Comment by ausil** [comment]
> Did you get a PIM372 display? I was expecting mine to be monochrome based on the Digi-Key description and was pleasantly surprised it was color. I’ll have to check the resolution as well. M

I did get the PIM372 from Digi-Key, I looked up a few places and could not find where it should be anything but 1024x768. it is even printed on the control board that it is that resolution. No problems with the colour, I have some very bright orange, hopefully, it looks okay.

**Comment by ausil** [comment]
I filed a product issue with digikey they updated the entry https://www.digikey.com/en/products/detail/pimoroni-ltd/PIM372/9565558 to say it is colour, however, they would not change the resolution as the docs state its 1024x768 and not 1152x864
